import type { Metadata } from "next";
import { Poppins, Nunito_Sans } from "next/font/google";

import "./globals.css";
import Layout from "@/components/layout";

export const metadata: Metadata = {
  title: "Mohammad Ali Ghasemi",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito-sans",
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${nunitoSans.variable} antialiased`}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
